/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_choochootrain_refocusing_activity_MainActivity */

#ifndef _Included_com_choochootrain_refocusing_activity_MainActivity
#define _Included_com_choochootrain_refocusing_activity_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_choochootrain_refocusing_activity_MainActivity
 * Method:    FindFeatures
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_choochootrain_refocusing_activity_MainActivity_FindFeatures
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
